# 所有的配置信息都可以在schema\common.py中找到
# 这里的配置可应用到所有任务的所有账号中
# 默认配置策略是任务优先；大白话就是：如果任务配置和common配置相同，优先使用任务配置
# 每个任务相同的配置可以移动到这里来，那么就可以把任务配置中的配置项注释掉

# 【选填】控制台是否打印调试内容，不清楚的不要开，否则控制台会非常的杂乱
# 默认关闭
debug: false
# 【选填】任务配置策略，任务优先还是common优先，1：common 2：任务
# 功能描述：common 表示common.yaml配置文件；任务表示对应的阅读配置文件，例如 klyd.yaml
# 默认为 2，任务优先
strategy: 2
# 【选填】阅读随机睡眠时间
# 默认随机阅读睡眠时间10-20秒，默认等待推送检测睡眠时间19（暂不随机）
delay:
  read_delay: [ 10, 20 ]
  push_delay: [ 19 ]
# 【选填】统一WxPusher的appToken， 默认为空，并注释（启用请删掉前面的“#”）
# 【！！注意！！】此配置会受上方的任务配置策略影响，
# 如果为2，请确认对应的任务中的appToken已被注释掉（行首加“#”）
#appToken: ""
# 【选填】是否启用“打印响应”功能，该功能主要用于调试，为避免生成较大的日志文件，故设置了此开关
# 【功能描述】打印网络的响应情况：响应状态码、发起请求者（账号名）、请求链接、请求头、请求体（如果有）、响应头、响应体（如果有）
is_log_response: false

