# 所有的配置信息都可以在schema\common.py中找到
# 这里的配置可应用到所有任务的所有账号中
# 默认配置策略是任务优先；大白话就是：如果任务配置和common配置相同，优先使用任务配置
# 每个任务相同的配置可以移动到这里来，那么就可以把任务配置中的配置项注释掉

# 【选填】控制台是否打印调试内容，不清楚的不要开，否则控制台会非常的杂乱
# 默认关闭
debug: false

# 【选填】任务配置策略，任务优先还是common优先，1：common 2：任务
# 功能描述：common 表示common.yaml配置文件；任务表示对应的阅读配置文件，例如 klyd.yaml
# 默认为 2，任务优先
strategy: 2

# 【选填】是否初始化 colorama 配置，默认初始化
# 功能描述：开关颜色渲染，true: 关闭渲染， false: 开启渲染
# Tips: 当此项为True青龙面板的颜色渲染会消失，这样或许可以避免不支持颜色显示的青龙面板出现乱码的现象
# Tips: 目前不知道什么原理，经过测试可以关掉颜色渲染，比较方便，哈哈
init_colorama: true

# 【选填】阅读随机睡眠时间
# 默认随机阅读睡眠时间10-20秒，默认等待推送检测睡眠时间19（暂不随机）
delay:
  read_delay: [ 10, 20 ]
  push_delay: [ 19 ]

# 【选填】推送方式，1: WxPusher 2: 企业微信（可单独配置）
# 功能描述：选择对应的推送平台，推送检测文章信息（可多选）
# Tips: 默认推送方式为 WxPusher
# 方法 1：
#push_types: [1, 2, 3]
# 方法 2：
#push_types:
#  - 1
#  - 2
#  - 3

# --------------WxPusher配置-------------------
# 【选填】统一WxPusher的appToken， 默认为空，并注释（启用请删掉前面的“#”）
# 【！！注意！！】此配置会受上方的任务配置策略影响，
# 如果为2，请确认对应的任务中的appToken已被注释掉（行首加“#”）
#appToken: ""

# 【选填】WxPusher中的主题ID（可单独配置），下面两种方式选择一个即可
# 配置方式 1：字符串 （此方式只能设置一个主题）
#topicIds: "123456"
# 配置方式2：数组 （此方式可以设置多个主题）
#topicIds: ["123456", "789123"]
# 或者下方数组格式
#topicIds:
#  - "123456"
#  - "789123"

# --------------WxPusher配置-------------------

# --------------企业微信配置-------------------
# 【选填】 是否使用 企业微信机器人推送（可单独配置）
# 功能描述：当 push_type为 2 时生效，默认为True
#use_robot: true
# 【必/选填】 企业微信机器人的webhook地址（可单独配置）
# 功能描述：当 use_robot为 true 时生效
#webhook_url: "https://..."

# 【必/选填】企业ID
# 功能描述：当 push_types==2 且 use_robot==true 时生效，此时此项必填
#corp_id: 123456
# 【必/选填】应用密钥
# 功能描述: 当 push_types==2 且 use_robot==true 时生效，此时此项必填
#corp_secret: "123456"
# 【必/选填】应用ID
# 功能描述: 当 push_types==2 且 use_robot==true 时生效，此时此项必填
#agent_id: 123456
# --------------企业微信配置-------------------

# --------------检测文章访问回调配置-------------------
# 此检测可以通过两种方式实现
# 方式一：本阅读程序，也就是不用安装部署其它，只需要按照下方配置项的提示来操作即可
# 方式二：单独部署对应的API程序，支持Docker一键部署，对应的github仓库地址如下：
# https://github.com/MoMingRose/WxReadDetect

# 【选填】是否使用websocket来完成检测文章的访问确认“回调”操作
# 功能描述：可以用来检测，用户是否访问了推送的检测文章链接
is_use_ws: true
# 【选/必填】websocket的域名及端口
# 功能描述：如果开启了“回调”操作，则此项必填！！！
# Tips: 过检测机子如果在外网，可以使用内网穿透青龙面板所在地址来完成回调操作
# Tips: 本地机子过检测，则把localhost改成你访问青龙面板的局域网地址
# Tips: ！！！ 注意青龙的docker配置中一定要映射16699端口，确保能够访问，才能进行后续的操作
# 公益API地址: mmlg.back1.hpnu.cn 或者 back1.hpnu.cn:16699
ws_host: "mmlg.back1.hpnu.cn"
# --------------检测文章访问回调配置-------------------

# 【选填】 最大检测未通过的账号数量
# 功能描述：当达到这个数量时，整个程序将会自动退出，默认为 0表示不作处理
max_failed_pass_count: 0

# 【选填】是否启用“打印响应”功能，该功能主要用于调试，为避免生成较大的日志文件，故设置了此开关
# 【功能描述】打印网络的响应情况：响应状态码、发起请求者（账号名）、请求链接、请求头、请求体（如果有）、响应头、响应体（如果有）
is_log_response: false

