# 【注意】
# 1. “#”符号表示注释，被注释掉的配置是【不会生效】，如果想让其生效，请去掉它
# 2. 请确保格式正确，否则会报错（只需要删除一个符号即可，其他的空格不用删除）
# 3. 实在不理解的可以前往 https://t.me/+A6PlLqiqK19mNzNl 问一问其他已了解的伙伴
# 4. 标注了“可单独配置”的，皆可以在对应的账号下添加，优先级更高

# 【选填】推送方式，1: WxPusher 2: 企业微信（可单独配置）
# 功能描述：选择对应的推送平台，推送检测文章信息（可多选）
# Tips: 默认推送方式为 WxPusher
# 方法 1：
#push_types: [1, 2, 3]
# 方法 2：
#push_types:
#  - 1
#  - 2
#  - 3

# --------------WxPusher配置-------------------
# 【必/选填】 WxPusher推送通知的appToken（可单独配置）
# 功能描述：当出现检测文章链接时，自动推送到对应账号
# Tips: 可以在云桌面搭建微信机器人，用来自动监听此消息，从而完成自动过检测功能
# Tips: 可在common.yaml为所有任务配置统一的appToken，此时这里的appToken可以省略
# Tips: 由于默认【配置策略】为【任务优先】，也就是此文件配置优先
# 故，如果这里是空字符串，则会覆盖common.yaml中的【配置策略】
#appToken: ""

# 【选填】WxPusher中的主题ID（可单独配置），下面两种方式选择一个即可
# 配置方式 1：字符串 （此方式只能设置一个主题）
#topicIds: "123456"
# 配置方式2：数组 （此方式可以设置多个主题）
#topicIds: ["123456", "789123"]
# 或者下方数组格式
#topicIds:
#  - "123456"
#  - "789123"
# --------------WxPusher配置-------------------

# --------------企业微信配置-------------------
# 【选填】 是否使用 企业微信机器人推送（可单独配置）
# 功能描述：当 push_type为 2 时生效，默认为True
#use_robot: true
# 【必/选填】 企业微信机器人的webhook地址（可单独配置）
# 功能描述：当 use_robot为 true 时生效
#webhook_url: "https://..."

# 【必/选填】企业ID
# 功能描述：当 push_types==2 且 use_robot==true 时生效，此时此项必填
#corp_id: "123456"
# 【必/选填】应用密钥
# 功能描述: 当 push_types==2 且 use_robot==true 时生效，此时此项必填
#corp_secret: "123456"
# 【必/选填】应用ID
# 功能描述: 当 push_types==2 且 use_robot==true 时生效，此时此项必填
#agent_id: 123456
# --------------企业微信配置-------------------

# 【选填】 全局延迟配置（可单独配置，直接在对应的账号中添加相同的格式即可）
# 功能描述：完成阅读，获取阅读文章前的睡眠时间
#delay:
#  # 模拟阅读时间，默认10-20
#  # Tips： 最小不能低于6秒
#  read_delay:
#    - 10
#    - 20
#  # 推送检测文章后的等待时间
#  push_delay:
#    - 19

# 【目前暂不支持】【选填】自动等待下批文章阅读（可单独配置），默认为 false
# 功能描述：出现如："下一批文章将在42分钟后到来"的消息后，是否自动睡眠
#wait_next_read: true
# 【目前暂不支持】【选填】 最大线程数，默认为 1
# 功能描述：设置线程池的最大线程数，每个线程可以单独跑一个账号
#max_thread_count: 1

# 【选填】 全局的支付宝提现账号（可单独配置），默认为空，则表示微信提现
#aliName: ""
#aliAccount: ""

# 【选填】是否需要提现，默认为 true，表示需要（可单独配置）
# 功能描述：可以用于阅读信息获取任务，限制提现请求
is_withdraw: true

# 【选填】全局提现金额（单位：元）（可单独配置）
#withdraw: 0.9

# 【必填】
account_data:
  # 账号名（自定义）
  账号1:
    # 【必填】
    # 抓包简述：开启抓包后，进入主页面，再回到抓包软件，筛选出链接中包含 user or workinfo，复制其中的cookie值即可
    cookie: "klyd_1"
    # 【必填】WxPusher中的用户UID，检测文章通知会单独发给这个微信用户
    uid: "1"

#  账号2:
#    cookie: "klyd_2"
#    uid: "2"
#  账号3:
#    cookie: "klyd_3"
#    uid: "3"
# 用于漏网之鱼检测（数据来源：幻生大佬）
biz_data:
  - "MzkxNTE3MzQ4MQ=="
  - "Mzg5MjM0MDEwNw=="
  - "MzUzODY4NzE2OQ=="
  - "MzkyMjE3MzYxMg=="
  - "MzkxNjMwNDIzOA=="
  - "Mzg3NzUxMjc5Mg=="
  - "Mzg4NTcwODE1NA=="
  - "Mzk0ODIxODE4OQ=="
  - "Mzg2NjUyMjI1NA=="
  - "MzIzMDczODg4Mw=="
  - "Mzg5ODUyMzYzMQ=="
  - "MzU0NzI5Mjc4OQ=="
  - "Mzg5MDgxODAzMg=="
  - "MzIzMDczODg4Mw=="
  - "MzkxNDU1NDEzNw=="