# 【选填】提现密码（全局配置）
# 功能描述：这里是全局配置，生效范围是所有账号（会被单独配置覆盖，其余未单独配置的则使用全局配置）
pwd: 6666

# 【选填】是否自动睡眠等待下一批文章的到来（全局配置，但会被单独配置覆盖，其余未单独配置的则使用全局配置）
wait_next_read: true

# 【选填】是否提现（全局配置，但会被单独配置覆盖，其余未单独配置的则使用全局配置）
is_withdraw: true

# 【选填】设置提现金额（全局配置，但会被单独配置覆盖，其余未单独配置的则使用全局配置）
# 不填，则会根据已有的提现选项，从大到小匹配
#withdraw: 3

account_data:
  # 这是用户名，可以自行更改
  账号1:
    # 【必填】主页面就有，无需抓包
    userShowId: 123456
    # 【必填】最好是手机号码后四位（当前是单独配置，会覆盖全局配置）
    pwd: 6666
    # 【选填】是否自动睡眠等待下一批文章的到来
    wait_next_read: true